import tkinter as tk
from all__operations import pagestructure as ps
window=tk.Tk()
window.geometry("500x500")
window.title("Team Dark Phoenix")
title__frame=tk.Frame(window,width=500,pady=20,padx=20)
title__frame.pack(side="top")
statment__frame=tk.Frame(window,width=500,pady=20,padx=20)
statment__frame.pack(side="top")
button1__frame=tk.Frame(window,width=500,pady=20,padx=20)
button1__frame.pack(side="top")
button2__frame=tk.Frame(window,width=500,pady=20,padx=20)
button2__frame.pack(side="top")
button3__frame=tk.Frame(window,width=500,pady=20,padx=20)
button3__frame.pack(side="top")
image__frame=tk.Frame(window,width=500,pady=20,padx=20)
image__frame.pack(side="top")
ps.first__page(title__frame=title__frame,window=window,statment__frame=statment__frame,button1__frame=button1__frame,button2__frame=button2__frame,button3__frame=button3__frame,image__frame=image__frame)
window.mainloop()